### ISSUE TITLE
Remove code that depends on migrate_plus

### ISSUE THREAD

**Issue by juliquiron** [Ymbra/migrate_default_content#49]
As far as the module is using migrate_pluse (https://github.com/Ymbra/migrate_default_content/blob/8.x-1.x/src/Event/MigrateEvent.php#L5) this module should be added as a dependency in the info file (https://github.com/Ymbra/migrate_default_content/blob/8.x-1.x/migrate_default_content.info.yml#L6)

thanks!

**Comment by rodrigoaguilera** [comment]
Thank you for pointing out code that is useless right now.

The actual plan is to deprecate what that event is doing (useful only for the CSV format) and recommed the YML format strongly.

If you need to use the HEAD of the 8.x-1.x branch and need that event you can enable the migrate_plus module.

I want to close the current open PR before making a relase

**Comment by tstoeckler** [comment]
> If you need to use the HEAD of the 8.x-1.x branch and need that event you can enable the migrate_plus module.

That's actually not always possible. If you are installing a site with Config Installer (or enabling this module in general via config import) then Migrate Plus might be enabled _after_ Migrate Default Content and then you get a fatal that the Migrate Plus event class cannot be found. So would be nice to resolve in this in some or another.

**Comment by rodrigoaguilera** [comment]
I thought about this and I think we should remove this Event class completely alongside the dependency since the CSV format is removed right now.

Support for CSV will come back but not for doing the kind of thing the event supports.

The documentation for this JSON trick should be removed also.

**Comment by rodrigoaguilera** [comment]
This issue was achieved but never closed
