### ISSUE TITLE
How to ensure a certain content type migration order

### ISSUE THREAD

**Issue by jameswilson** [Ymbra/migrate_default_content#68]
We have a content type with machine name `basic_page` and we wrote a default content migration for it, whereby `node/1` ended up as the Drupal front page.

Later we added another migration for a node type called `resource`, but somehow the resources are being migrated before the basic pages, resulting in `node/1` belonging to the wrong content type.

I might have assumed that the order would default to alphabetical, but that seems to not be the case.

Is there a way, eg, either with the Drupal 8 migration process or with this module's own configuration  to ensure that a certain content type, or specific entry in a specific yaml file gets processed and migrated first, so that we can ensure node/1 ends up as a specific node?

**Comment by rodrigoaguilera** [comment]
Hello @jameswilson 
Thanks for the interest in the module :)

I haven't tried it but I think you can just specify the property "nid" for nodes the same as other fields.
We use UUIDs all the time. Tt shouldn't be any different.

Once this goes in
https://www.drupal.org/project/drupal/issues/2353611
you can achieve the frontpage configuration also by uuid

**Comment by jameswilson** [comment]
@rodrigoaguilera thanks for the prompt response. I was able to confirm that using `nid: 1` in the yaml file actually worked, to my pleasant surprise!

**Comment by jameswilson** [comment]
If anyone else hits this issue and really does need a specific order which is not solved by adding the `tid`s, you might give [Migrate Manifest](https://www.drupal.org/project/migrate_manifest) module a try.
